from ... import *
from pyrogram import *
from pyrogram.types import *


@app.on_message(filters.command(["gen", "ccgen"], [".", "!", "/"]))
async def gen_cc(client, message):
    if len(message.command) < 2:
        return await message.reply_text(
            "**⚠️Please Give Me a Bin To\nGenerate Cc ...⚠️**"
        )
    try:
        await message.delete()
    except:
        pass
    aux = await message.reply_text("**✅Generating ...**")
    bin = message.text.split(None, 1)[1]
    if len(bin) < 6:
        return await aux.edit("**🚫 Wrong Bin❗...**")
    try:
        resp = await api.ccgen(bin, 10)
        cards = resp.liveCC
        name = message.from_user.first_name
        await aux.edit(f"""
❅ ✧ 𝗕𝗥𝗢𝗞𝗘𝗡 𝗫 𝗖𝗖 𝗚𝗘𝗡𝗘𝗥𝗔𝗧𝗢𝗥 ✧ ❅

`{cards[0]}`\n`{cards[1]}`\n`{cards[2]}`
`{cards[3]}`\n`{cards[4]}`\n`{cards[5]}`
`{cards[6]}`\n`{cards[7]}`\n`{cards[8]}`
`{cards[9]}`

**-----------------------------**

**🪪 Generated By:** {name}

**💳 BIN:** `{bin}`
**🪪 Dev:** [『𝙼𝚁』〆𝔅𝔯𝔬𝔨𝔢𝔫](https://t.me/AboutBrokenx)
**⏳ Time Taken:** `{resp.took}`
𝗕𝗶𝗻 𝗟𝗼𝗼𝗸𝘂𝗽 𝗥𝗲𝘀𝘂𝗹𝘁 🔍
**🔎INFO :** `{resp.results[0].bin}`\n\n"""
        )
    except Exception as e:
        return await aux.edit(f"**Error:** `{e}`")

  
